# Generated by Django 6.0.3 on 2026-04-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="manager_approved",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
